"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const authMiddlaware_1 = require("../middlewares/authMiddlaware");
const citaController_1 = require("../controllers/citaController");
const router = (0, express_1.Router)();
router.post('/newAppointment', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)(['User', 'administrador', 'empleado']), citaController_1.newCita);
router.post('/updateDate/:id', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)(['User', 'administrador', 'empleado']), citaController_1.updateCita);
router.put('/updateStatusAppointment/:id', authMiddlaware_1.authenticate, citaController_1.updateCitaEstado);
router.get('/getPendingAppointment', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)(['administrador', 'empleado']), citaController_1.getCitas);
router.get('/getUserAppointment', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)(['User']), citaController_1.getUserAppointment);
router.get('/GetAppointments/:fecha', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)(['User', 'empleado', 'administrador']), citaController_1.GetAppointmentDate);
exports.default = router;
