"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const employeeController_1 = require("../controllers/employeeController");
const authMiddlaware_1 = require("../middlewares/authMiddlaware");
const router = (0, express_1.Router)();
router.post('/newEmployee', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)('administrador'), employeeController_1.createEmployee);
router.get('/employees', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)('administrador'), employeeController_1.getAllEmployees);
router.get('/employee/:cedulaEmpleado', authMiddlaware_1.authenticate, employeeController_1.getEmployeesById);
router.put('/updateEmployee/:cedulaEmpleado', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)('administrador'), employeeController_1.updateEmployeed);
router.delete('/deleteEmployee/:cedulaEmpleado', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)('administrador'), employeeController_1.deleteEmployee);
router.get('/employeServices/:cargo', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)(['User', 'administrador']), employeeController_1.getEmployeesServices);
exports.default = router;
