"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const petControllers_1 = require("../controllers/petControllers");
const authMiddlaware_1 = require("../middlewares/authMiddlaware");
const router = (0, express_1.Router)();
router.post('/newPet', authMiddlaware_1.authenticate, petControllers_1.createPet);
router.get('/Pets', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)('administrador'), petControllers_1.getAllPet);
router.get('/Pet', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)(['User']), petControllers_1.findPetsUser);
router.put('/UpdatePet/:idMascota', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)(['User', 'administrador']), petControllers_1.updatePet);
router.put('/DeletePet/:idMascota', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)(['User', 'administrador']), petControllers_1.deletePet);
router.get('/PetsUser', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)(['administrador', 'empleado']), petControllers_1.petsUser);
exports.default = router;
