"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const productoController_1 = require("../controllers/productoController");
const authMiddlaware_1 = require("../middlewares/authMiddlaware");
const router = (0, express_1.Router)();
router.post('/producto', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)('administrador'), productoController_1.createProducto);
router.get('/products', productoController_1.getProducts);
router.put('/producto/:idProducto', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)('administrador'), productoController_1.updateProducto);
router.delete('/producto/:idProducto', authMiddlaware_1.authenticate, (0, authMiddlaware_1.accessRole)('administrador'), productoController_1.deleteProducto);
router.post('/create_preference', productoController_1.preferences_);
router.get('/webhook', productoController_1.webhook);
exports.default = router;
